// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminBlockUserReducer from "../admin_block_user_reducer";
import AdminDeleteSprintReducer from "../admin_delete_sprint_reducer";
import AdminDeleteUserReducer from "../admin_delete_user_reducer";
import AdminSetSprintReducer from "../admin_set_sprint_reducer";
import AdminUnblockUserReducer from "../admin_unblock_user_reducer";
import AdminWipeReducer from "../admin_wipe_reducer";
import ApproveDemoPaymentReducer from "../approve_demo_payment_reducer";
import ArchiveSprintReducer from "../archive_sprint_reducer";
import CancelDemoPaymentReducer from "../cancel_demo_payment_reducer";
import ClaimAdminReducer from "../claim_admin_reducer";
import ClaimUsernameReducer from "../claim_username_reducer";
import CommitSupportReducer from "../commit_support_reducer";
import CreateDemoPaymentSessionReducer from "../create_demo_payment_session_reducer";
import CreateSprintReducer from "../create_sprint_reducer";
import CreateSprintV2Reducer from "../create_sprint_v_2_reducer";
import DeleteAccountReducer from "../delete_account_reducer";
import DeleteSprintReducer from "../delete_sprint_reducer";
import EnterSprintReducer from "../enter_sprint_reducer";
import FailDemoPaymentReducer from "../fail_demo_payment_reducer";
import GrantAdminReducer from "../grant_admin_reducer";
import PlaceBidReducer from "../place_bid_reducer";
import RateBuilderReducer from "../rate_builder_reducer";
import RecordEventReducer from "../record_event_reducer";
import RegisterReducer from "../register_reducer";
import RetryFailedEmailsReducer from "../retry_failed_emails_reducer";
import RevokeAdminReducer from "../revoke_admin_reducer";
import SaveProfileReducer from "../save_profile_reducer";
import SendContactReducer from "../send_contact_reducer";
import SendInviteReducer from "../send_invite_reducer";
import SetAdminCodeReducer from "../set_admin_code_reducer";
import SetEmailConfigReducer from "../set_email_config_reducer";
import SetSiteConfigReducer from "../set_site_config_reducer";
import ToggleInterestReducer from "../toggle_interest_reducer";
import UpdateSprintReducer from "../update_sprint_reducer";
import UpdateSprintDetailsReducer from "../update_sprint_details_reducer";

export type AdminBlockUserParams = __Infer<typeof AdminBlockUserReducer>;
export type AdminDeleteSprintParams = __Infer<typeof AdminDeleteSprintReducer>;
export type AdminDeleteUserParams = __Infer<typeof AdminDeleteUserReducer>;
export type AdminSetSprintParams = __Infer<typeof AdminSetSprintReducer>;
export type AdminUnblockUserParams = __Infer<typeof AdminUnblockUserReducer>;
export type AdminWipeParams = __Infer<typeof AdminWipeReducer>;
export type ApproveDemoPaymentParams = __Infer<typeof ApproveDemoPaymentReducer>;
export type ArchiveSprintParams = __Infer<typeof ArchiveSprintReducer>;
export type CancelDemoPaymentParams = __Infer<typeof CancelDemoPaymentReducer>;
export type ClaimAdminParams = __Infer<typeof ClaimAdminReducer>;
export type ClaimUsernameParams = __Infer<typeof ClaimUsernameReducer>;
export type CommitSupportParams = __Infer<typeof CommitSupportReducer>;
export type CreateDemoPaymentSessionParams = __Infer<typeof CreateDemoPaymentSessionReducer>;
export type CreateSprintParams = __Infer<typeof CreateSprintReducer>;
export type CreateSprintV2Params = __Infer<typeof CreateSprintV2Reducer>;
export type DeleteAccountParams = __Infer<typeof DeleteAccountReducer>;
export type DeleteSprintParams = __Infer<typeof DeleteSprintReducer>;
export type EnterSprintParams = __Infer<typeof EnterSprintReducer>;
export type FailDemoPaymentParams = __Infer<typeof FailDemoPaymentReducer>;
export type GrantAdminParams = __Infer<typeof GrantAdminReducer>;
export type PlaceBidParams = __Infer<typeof PlaceBidReducer>;
export type RateBuilderParams = __Infer<typeof RateBuilderReducer>;
export type RecordEventParams = __Infer<typeof RecordEventReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RetryFailedEmailsParams = __Infer<typeof RetryFailedEmailsReducer>;
export type RevokeAdminParams = __Infer<typeof RevokeAdminReducer>;
export type SaveProfileParams = __Infer<typeof SaveProfileReducer>;
export type SendContactParams = __Infer<typeof SendContactReducer>;
export type SendInviteParams = __Infer<typeof SendInviteReducer>;
export type SetAdminCodeParams = __Infer<typeof SetAdminCodeReducer>;
export type SetEmailConfigParams = __Infer<typeof SetEmailConfigReducer>;
export type SetSiteConfigParams = __Infer<typeof SetSiteConfigReducer>;
export type ToggleInterestParams = __Infer<typeof ToggleInterestReducer>;
export type UpdateSprintParams = __Infer<typeof UpdateSprintReducer>;
export type UpdateSprintDetailsParams = __Infer<typeof UpdateSprintDetailsReducer>;

