// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  title: __t.string(),
  tagline: __t.string(),
  description: __t.string(),
  nextStep: __t.string(),
  builderName: __t.string(),
  builderBio: __t.string(),
  builderCity: __t.string(),
  category: __t.string(),
  stage: __t.string(),
  goalAmount: __t.u64(),
  durationSeconds: __t.u64(),
  opensInSeconds: __t.u64(),
  fundPct: __t.byteArray(),
  perkTitles: __t.array(__t.string()),
  perkDescriptions: __t.array(__t.string()),
  perkSlots: __t.array(__t.u32()),
  perkMinAmounts: __t.array(__t.u64()),
  journeyDates: __t.array(__t.string()),
  journeyTexts: __t.array(__t.string()),
  imageThumbs: __t.array(__t.string()),
  imageFulls: __t.array(__t.string()),
  extraAllocLabels: __t.array(__t.string()),
  extraAllocPcts: __t.byteArray(),
};
