// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  sprintId: __t.u64().name("sprint_id"),
  supporterIdentity: __t.identity().name("supporter_identity"),
  supporterUsername: __t.string().name("supporter_username"),
  amount: __t.u64(),
  optionIds: __t.array(__t.u64()).name("option_ids"),
  quantities: __t.array(__t.u32()),
  conditionLabel: __t.string().name("condition_label"),
  status: __t.string(),
  outcome: __t.string(),
  errorText: __t.string().name("error_text"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  approvedAt: __t.option(__t.timestamp()).name("approved_at"),
  commitmentId: __t.option(__t.u64()).name("commitment_id"),
  mockRef: __t.string().name("mock_ref"),
  goalCrossed: __t.bool().name("goal_crossed"),
  committedAfter: __t.u64().name("committed_after"),
  supportersAfter: __t.u32().name("supporters_after"),
});
