// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  kind: __t.string(),
  sprintId: __t.u64().name("sprint_id"),
  sessionCode: __t.string().name("session_code"),
  identity: __t.identity(),
  amount: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
});
