// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.9.0 (commit 9e0d92412ff2248f401a8ad12d535f2b5ac30912).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdminBlockUserReducer from "./admin_block_user_reducer";
import AdminDeleteSprintReducer from "./admin_delete_sprint_reducer";
import AdminDeleteUserReducer from "./admin_delete_user_reducer";
import AdminSetSprintReducer from "./admin_set_sprint_reducer";
import AdminUnblockUserReducer from "./admin_unblock_user_reducer";
import AdminWipeReducer from "./admin_wipe_reducer";
import ApproveDemoPaymentReducer from "./approve_demo_payment_reducer";
import ArchiveSprintReducer from "./archive_sprint_reducer";
import CancelDemoPaymentReducer from "./cancel_demo_payment_reducer";
import ClaimAdminReducer from "./claim_admin_reducer";
import ClaimUsernameReducer from "./claim_username_reducer";
import CommitSupportReducer from "./commit_support_reducer";
import CreateDemoPaymentSessionReducer from "./create_demo_payment_session_reducer";
import CreateSprintReducer from "./create_sprint_reducer";
import CreateSprintV2Reducer from "./create_sprint_v_2_reducer";
import DeleteAccountReducer from "./delete_account_reducer";
import DeleteSprintReducer from "./delete_sprint_reducer";
import EnterSprintReducer from "./enter_sprint_reducer";
import FailDemoPaymentReducer from "./fail_demo_payment_reducer";
import GrantAdminReducer from "./grant_admin_reducer";
import PlaceBidReducer from "./place_bid_reducer";
import RateBuilderReducer from "./rate_builder_reducer";
import RecordEventReducer from "./record_event_reducer";
import RegisterReducer from "./register_reducer";
import RetryFailedEmailsReducer from "./retry_failed_emails_reducer";
import RevokeAdminReducer from "./revoke_admin_reducer";
import SaveProfileReducer from "./save_profile_reducer";
import SendContactReducer from "./send_contact_reducer";
import SendInviteReducer from "./send_invite_reducer";
import SetAdminCodeReducer from "./set_admin_code_reducer";
import SetEmailConfigReducer from "./set_email_config_reducer";
import SetSiteConfigReducer from "./set_site_config_reducer";
import ToggleInterestReducer from "./toggle_interest_reducer";
import UpdateSprintReducer from "./update_sprint_reducer";
import UpdateSprintDetailsReducer from "./update_sprint_details_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AdminRow from "./admin_table";
import AllocationItemRow from "./allocation_item_table";
import BlockedUserRow from "./blocked_user_table";
import BuilderRatingRow from "./builder_rating_table";
import CommitmentItemRow from "./commitment_item_table";
import DemoPaymentSessionRow from "./demo_payment_session_table";
import EventLogRow from "./event_log_table";
import FinalResultRow from "./final_result_table";
import InterestRow from "./interest_table";
import InviteRow from "./invite_table";
import JourneyEntryRow from "./journey_entry_table";
import ProfileRow from "./profile_table";
import RoomPresenceRow from "./room_presence_table";
import SiteConfigRow from "./site_config_table";
import SprintRow from "./sprint_table";
import SprintMediaRow from "./sprint_media_table";
import SprintOwnerRow from "./sprint_owner_table";
import SupportCommitmentRow from "./support_commitment_table";
import SupportOptionRow from "./support_option_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  admin: __table({
    name: 'admin',
    indexes: [
      { accessor: 'identity', name: 'admin_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'admin_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AdminRow),
  allocationItem: __table({
    name: 'allocation_item',
    indexes: [
      { accessor: 'id', name: 'allocation_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'allocation_item_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'allocation_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AllocationItemRow),
  blockedUser: __table({
    name: 'blocked_user',
    indexes: [
      { accessor: 'identity', name: 'blocked_user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'blocked_user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, BlockedUserRow),
  builderRating: __table({
    name: 'builder_rating',
    indexes: [
      { accessor: 'builderIdentity', name: 'builder_rating_builder_identity_idx_btree', algorithm: 'btree', columns: [
        'builderIdentity',
      ] },
      { accessor: 'id', name: 'builder_rating_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'builder_rating_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BuilderRatingRow),
  commitmentItem: __table({
    name: 'commitment_item',
    indexes: [
      { accessor: 'commitmentId', name: 'commitment_item_commitment_id_idx_btree', algorithm: 'btree', columns: [
        'commitmentId',
      ] },
      { accessor: 'id', name: 'commitment_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'supportOptionId', name: 'commitment_item_support_option_id_idx_btree', algorithm: 'btree', columns: [
        'supportOptionId',
      ] },
    ],
    constraints: [
      { name: 'commitment_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommitmentItemRow),
  demoPaymentSession: __table({
    name: 'demo_payment_session',
    indexes: [
      { accessor: 'code', name: 'demo_payment_session_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'id', name: 'demo_payment_session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'demo_payment_session_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'demo_payment_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DemoPaymentSessionRow),
  eventLog: __table({
    name: 'event_log',
    indexes: [
      { accessor: 'id', name: 'event_log_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'kind', name: 'event_log_kind_idx_btree', algorithm: 'btree', columns: [
        'kind',
      ] },
    ],
    constraints: [
      { name: 'event_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventLogRow),
  finalResult: __table({
    name: 'final_result',
    indexes: [
      { accessor: 'sprintId', name: 'final_result_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'final_result_sprint_id_key', constraint: 'unique', columns: ['sprintId'] },
    ],
  }, FinalResultRow),
  interest: __table({
    name: 'interest',
    indexes: [
      { accessor: 'id', name: 'interest_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'interest_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'interest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InterestRow),
  invite: __table({
    name: 'invite',
    indexes: [
      { accessor: 'id', name: 'invite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'invitedUsername', name: 'invite_invited_username_idx_btree', algorithm: 'btree', columns: [
        'invitedUsername',
      ] },
      { accessor: 'sprintId', name: 'invite_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'invite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InviteRow),
  journeyEntry: __table({
    name: 'journey_entry',
    indexes: [
      { accessor: 'id', name: 'journey_entry_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'journey_entry_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'journey_entry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, JourneyEntryRow),
  profile: __table({
    name: 'profile',
    indexes: [
      { accessor: 'identity', name: 'profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ProfileRow),
  roomPresence: __table({
    name: 'room_presence',
    indexes: [
      { accessor: 'connectionId', name: 'room_presence_connection_id_idx_btree', algorithm: 'btree', columns: [
        'connectionId',
      ] },
      { accessor: 'sprintId', name: 'room_presence_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'room_presence_connection_id_key', constraint: 'unique', columns: ['connectionId'] },
    ],
  }, RoomPresenceRow),
  siteConfig: __table({
    name: 'site_config',
    indexes: [
      { accessor: 'key', name: 'site_config_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'site_config_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SiteConfigRow),
  sprint: __table({
    name: 'sprint',
    indexes: [
      { accessor: 'id', name: 'sprint_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'sprint_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SprintRow),
  sprintMedia: __table({
    name: 'sprint_media',
    indexes: [
      { accessor: 'id', name: 'sprint_media_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'sprint_media_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'sprint_media_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SprintMediaRow),
  sprintOwner: __table({
    name: 'sprint_owner',
    indexes: [
      { accessor: 'identity', name: 'sprint_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'sprintId', name: 'sprint_owner_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'sprint_owner_sprint_id_key', constraint: 'unique', columns: ['sprintId'] },
    ],
  }, SprintOwnerRow),
  supportCommitment: __table({
    name: 'support_commitment',
    indexes: [
      { accessor: 'id', name: 'support_commitment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'support_commitment_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'support_commitment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SupportCommitmentRow),
  supportOption: __table({
    name: 'support_option',
    indexes: [
      { accessor: 'id', name: 'support_option_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sprintId', name: 'support_option_sprint_id_idx_btree', algorithm: 'btree', columns: [
        'sprintId',
      ] },
    ],
    constraints: [
      { name: 'support_option_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SupportOptionRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("admin_block_user", AdminBlockUserReducer),
  __reducerSchema("admin_delete_sprint", AdminDeleteSprintReducer),
  __reducerSchema("admin_delete_user", AdminDeleteUserReducer),
  __reducerSchema("admin_set_sprint", AdminSetSprintReducer),
  __reducerSchema("admin_unblock_user", AdminUnblockUserReducer),
  __reducerSchema("admin_wipe", AdminWipeReducer),
  __reducerSchema("approve_demo_payment", ApproveDemoPaymentReducer),
  __reducerSchema("archive_sprint", ArchiveSprintReducer),
  __reducerSchema("cancel_demo_payment", CancelDemoPaymentReducer),
  __reducerSchema("claim_admin", ClaimAdminReducer),
  __reducerSchema("claim_username", ClaimUsernameReducer),
  __reducerSchema("commit_support", CommitSupportReducer),
  __reducerSchema("create_demo_payment_session", CreateDemoPaymentSessionReducer),
  __reducerSchema("create_sprint", CreateSprintReducer),
  __reducerSchema("create_sprint_v_2", CreateSprintV2Reducer),
  __reducerSchema("delete_account", DeleteAccountReducer),
  __reducerSchema("delete_sprint", DeleteSprintReducer),
  __reducerSchema("enter_sprint", EnterSprintReducer),
  __reducerSchema("fail_demo_payment", FailDemoPaymentReducer),
  __reducerSchema("grant_admin", GrantAdminReducer),
  __reducerSchema("place_bid", PlaceBidReducer),
  __reducerSchema("rate_builder", RateBuilderReducer),
  __reducerSchema("record_event", RecordEventReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("retry_failed_emails", RetryFailedEmailsReducer),
  __reducerSchema("revoke_admin", RevokeAdminReducer),
  __reducerSchema("save_profile", SaveProfileReducer),
  __reducerSchema("send_contact", SendContactReducer),
  __reducerSchema("send_invite", SendInviteReducer),
  __reducerSchema("set_admin_code", SetAdminCodeReducer),
  __reducerSchema("set_email_config", SetEmailConfigReducer),
  __reducerSchema("set_site_config", SetSiteConfigReducer),
  __reducerSchema("toggle_interest", ToggleInterestReducer),
  __reducerSchema("update_sprint", UpdateSprintReducer),
  __reducerSchema("update_sprint_details", UpdateSprintDetailsReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `allocationItem` instead. This alias will be removed in the next major version. */
    readonly "allocation_item": Omit<typeof tablesSchema.schemaType.tables["allocationItem"], "accessorName"> & { readonly accessorName: "allocation_item" };
    /** @deprecated Use `blockedUser` instead. This alias will be removed in the next major version. */
    readonly "blocked_user": Omit<typeof tablesSchema.schemaType.tables["blockedUser"], "accessorName"> & { readonly accessorName: "blocked_user" };
    /** @deprecated Use `builderRating` instead. This alias will be removed in the next major version. */
    readonly "builder_rating": Omit<typeof tablesSchema.schemaType.tables["builderRating"], "accessorName"> & { readonly accessorName: "builder_rating" };
    /** @deprecated Use `commitmentItem` instead. This alias will be removed in the next major version. */
    readonly "commitment_item": Omit<typeof tablesSchema.schemaType.tables["commitmentItem"], "accessorName"> & { readonly accessorName: "commitment_item" };
    /** @deprecated Use `demoPaymentSession` instead. This alias will be removed in the next major version. */
    readonly "demo_payment_session": Omit<typeof tablesSchema.schemaType.tables["demoPaymentSession"], "accessorName"> & { readonly accessorName: "demo_payment_session" };
    /** @deprecated Use `eventLog` instead. This alias will be removed in the next major version. */
    readonly "event_log": Omit<typeof tablesSchema.schemaType.tables["eventLog"], "accessorName"> & { readonly accessorName: "event_log" };
    /** @deprecated Use `finalResult` instead. This alias will be removed in the next major version. */
    readonly "final_result": Omit<typeof tablesSchema.schemaType.tables["finalResult"], "accessorName"> & { readonly accessorName: "final_result" };
    /** @deprecated Use `journeyEntry` instead. This alias will be removed in the next major version. */
    readonly "journey_entry": Omit<typeof tablesSchema.schemaType.tables["journeyEntry"], "accessorName"> & { readonly accessorName: "journey_entry" };
    /** @deprecated Use `roomPresence` instead. This alias will be removed in the next major version. */
    readonly "room_presence": Omit<typeof tablesSchema.schemaType.tables["roomPresence"], "accessorName"> & { readonly accessorName: "room_presence" };
    /** @deprecated Use `siteConfig` instead. This alias will be removed in the next major version. */
    readonly "site_config": Omit<typeof tablesSchema.schemaType.tables["siteConfig"], "accessorName"> & { readonly accessorName: "site_config" };
    /** @deprecated Use `sprintMedia` instead. This alias will be removed in the next major version. */
    readonly "sprint_media": Omit<typeof tablesSchema.schemaType.tables["sprintMedia"], "accessorName"> & { readonly accessorName: "sprint_media" };
    /** @deprecated Use `sprintOwner` instead. This alias will be removed in the next major version. */
    readonly "sprint_owner": Omit<typeof tablesSchema.schemaType.tables["sprintOwner"], "accessorName"> & { readonly accessorName: "sprint_owner" };
    /** @deprecated Use `supportCommitment` instead. This alias will be removed in the next major version. */
    readonly "support_commitment": Omit<typeof tablesSchema.schemaType.tables["supportCommitment"], "accessorName"> & { readonly accessorName: "support_commitment" };
    /** @deprecated Use `supportOption` instead. This alias will be removed in the next major version. */
    readonly "support_option": Omit<typeof tablesSchema.schemaType.tables["supportOption"], "accessorName"> & { readonly accessorName: "support_option" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.9.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "allocation_item": "allocationItem",
  "blocked_user": "blockedUser",
  "builder_rating": "builderRating",
  "commitment_item": "commitmentItem",
  "demo_payment_session": "demoPaymentSession",
  "event_log": "eventLog",
  "final_result": "finalResult",
  "journey_entry": "journeyEntry",
  "room_presence": "roomPresence",
  "site_config": "siteConfig",
  "sprint_media": "sprintMedia",
  "sprint_owner": "sprintOwner",
  "support_commitment": "supportCommitment",
  "support_option": "supportOption",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `allocationItem` instead. This alias will be removed in the next major version. */
  readonly "allocation_item": __DbViewBase["allocationItem"];
  /** @deprecated Use `blockedUser` instead. This alias will be removed in the next major version. */
  readonly "blocked_user": __DbViewBase["blockedUser"];
  /** @deprecated Use `builderRating` instead. This alias will be removed in the next major version. */
  readonly "builder_rating": __DbViewBase["builderRating"];
  /** @deprecated Use `commitmentItem` instead. This alias will be removed in the next major version. */
  readonly "commitment_item": __DbViewBase["commitmentItem"];
  /** @deprecated Use `demoPaymentSession` instead. This alias will be removed in the next major version. */
  readonly "demo_payment_session": __DbViewBase["demoPaymentSession"];
  /** @deprecated Use `eventLog` instead. This alias will be removed in the next major version. */
  readonly "event_log": __DbViewBase["eventLog"];
  /** @deprecated Use `finalResult` instead. This alias will be removed in the next major version. */
  readonly "final_result": __DbViewBase["finalResult"];
  /** @deprecated Use `journeyEntry` instead. This alias will be removed in the next major version. */
  readonly "journey_entry": __DbViewBase["journeyEntry"];
  /** @deprecated Use `roomPresence` instead. This alias will be removed in the next major version. */
  readonly "room_presence": __DbViewBase["roomPresence"];
  /** @deprecated Use `siteConfig` instead. This alias will be removed in the next major version. */
  readonly "site_config": __DbViewBase["siteConfig"];
  /** @deprecated Use `sprintMedia` instead. This alias will be removed in the next major version. */
  readonly "sprint_media": __DbViewBase["sprintMedia"];
  /** @deprecated Use `sprintOwner` instead. This alias will be removed in the next major version. */
  readonly "sprint_owner": __DbViewBase["sprintOwner"];
  /** @deprecated Use `supportCommitment` instead. This alias will be removed in the next major version. */
  readonly "support_commitment": __DbViewBase["supportCommitment"];
  /** @deprecated Use `supportOption` instead. This alias will be removed in the next major version. */
  readonly "support_option": __DbViewBase["supportOption"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `allocationItem` instead. This alias will be removed in the next major version. */
  readonly "allocation_item": __TablesBase["allocationItem"];
  /** @deprecated Use `blockedUser` instead. This alias will be removed in the next major version. */
  readonly "blocked_user": __TablesBase["blockedUser"];
  /** @deprecated Use `builderRating` instead. This alias will be removed in the next major version. */
  readonly "builder_rating": __TablesBase["builderRating"];
  /** @deprecated Use `commitmentItem` instead. This alias will be removed in the next major version. */
  readonly "commitment_item": __TablesBase["commitmentItem"];
  /** @deprecated Use `demoPaymentSession` instead. This alias will be removed in the next major version. */
  readonly "demo_payment_session": __TablesBase["demoPaymentSession"];
  /** @deprecated Use `eventLog` instead. This alias will be removed in the next major version. */
  readonly "event_log": __TablesBase["eventLog"];
  /** @deprecated Use `finalResult` instead. This alias will be removed in the next major version. */
  readonly "final_result": __TablesBase["finalResult"];
  /** @deprecated Use `journeyEntry` instead. This alias will be removed in the next major version. */
  readonly "journey_entry": __TablesBase["journeyEntry"];
  /** @deprecated Use `roomPresence` instead. This alias will be removed in the next major version. */
  readonly "room_presence": __TablesBase["roomPresence"];
  /** @deprecated Use `siteConfig` instead. This alias will be removed in the next major version. */
  readonly "site_config": __TablesBase["siteConfig"];
  /** @deprecated Use `sprintMedia` instead. This alias will be removed in the next major version. */
  readonly "sprint_media": __TablesBase["sprintMedia"];
  /** @deprecated Use `sprintOwner` instead. This alias will be removed in the next major version. */
  readonly "sprint_owner": __TablesBase["sprintOwner"];
  /** @deprecated Use `supportCommitment` instead. This alias will be removed in the next major version. */
  readonly "support_commitment": __TablesBase["supportCommitment"];
  /** @deprecated Use `supportOption` instead. This alias will be removed in the next major version. */
  readonly "support_option": __TablesBase["supportOption"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

