// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  displayName: __t.string().name("display_name"),
  createdAt: __t.timestamp().name("created_at"),
  username: __t.string(),
  bio: __t.string(),
  contact: __t.string(),
  location: __t.string(),
  socialX: __t.string().name("social_x"),
  socialLinkedin: __t.string().name("social_linkedin"),
  socialInstagram: __t.string().name("social_instagram"),
});
