// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  description: __t.string(),
  nextStep: __t.string().name("next_step"),
  mediaUrl: __t.string().name("media_url"),
  builderName: __t.string().name("builder_name"),
  goalAmount: __t.u64().name("goal_amount"),
  committedAmount: __t.u64().name("committed_amount"),
  supporterCount: __t.u32().name("supporter_count"),
  deadline: __t.timestamp(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  peakPresence: __t.u32().name("peak_presence"),
  builderBio: __t.string().name("builder_bio"),
  reserveAmount: __t.u64().name("reserve_amount"),
  tagline: __t.string(),
  category: __t.string(),
  stage: __t.string(),
  builderCity: __t.string().name("builder_city"),
  builderUsername: __t.string().name("builder_username"),
  fundToolingPct: __t.u8().name("fund_tooling_pct"),
  fundComponentsPct: __t.u8().name("fund_components_pct"),
  fundCertPct: __t.u8().name("fund_cert_pct"),
  fundBufferPct: __t.u8().name("fund_buffer_pct"),
  opensAt: __t.timestamp().name("opens_at"),
  interestCount: __t.u32().name("interest_count"),
});
