// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sprintId: __t.u64().name("sprint_id"),
  identity: __t.identity(),
  amount: __t.u64(),
  supportOptionId: __t.option(__t.u64()).name("support_option_id"),
  mockTransactionId: __t.string().name("mock_transaction_id"),
  createdAt: __t.timestamp().name("created_at"),
  quantity: __t.u32(),
  reserveAmount: __t.u64().name("reserve_amount"),
});
