// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
  username: __t.string(),
  grantedAt: __t.timestamp(),
});
export type Admin = __Infer<typeof Admin>;

export const AllocationItem = __t.object("AllocationItem", {
  id: __t.u64(),
  sprintId: __t.u64(),
  label: __t.string(),
  pct: __t.u8(),
});
export type AllocationItem = __Infer<typeof AllocationItem>;

export const AppConfig = __t.object("AppConfig", {
  key: __t.string(),
  value: __t.string(),
});
export type AppConfig = __Infer<typeof AppConfig>;

export const BlockedUser = __t.object("BlockedUser", {
  identity: __t.identity(),
  username: __t.string(),
  reason: __t.string(),
  blockedAt: __t.timestamp(),
});
export type BlockedUser = __Infer<typeof BlockedUser>;

export const BuilderRating = __t.object("BuilderRating", {
  id: __t.u64(),
  builderIdentity: __t.identity(),
  raterIdentity: __t.identity(),
  sprintId: __t.u64(),
  stars: __t.u8(),
  createdAt: __t.timestamp(),
});
export type BuilderRating = __Infer<typeof BuilderRating>;

export const CommitmentItem = __t.object("CommitmentItem", {
  id: __t.u64(),
  commitmentId: __t.u64(),
  supportOptionId: __t.u64(),
  quantity: __t.u32(),
});
export type CommitmentItem = __Infer<typeof CommitmentItem>;

export const ContactMessage = __t.object("ContactMessage", {
  id: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  email: __t.string(),
  message: __t.string(),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
});
export type ContactMessage = __Infer<typeof ContactMessage>;

export const DemoPaymentSession = __t.object("DemoPaymentSession", {
  id: __t.u64(),
  code: __t.string(),
  sprintId: __t.u64(),
  supporterIdentity: __t.identity(),
  supporterUsername: __t.string(),
  amount: __t.u64(),
  optionIds: __t.array(__t.u64()),
  quantities: __t.array(__t.u32()),
  conditionLabel: __t.string(),
  status: __t.string(),
  outcome: __t.string(),
  errorText: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  approvedAt: __t.option(__t.timestamp()),
  commitmentId: __t.option(__t.u64()),
  mockRef: __t.string(),
  goalCrossed: __t.bool(),
  committedAfter: __t.u64(),
  supportersAfter: __t.u32(),
});
export type DemoPaymentSession = __Infer<typeof DemoPaymentSession>;

export const EmailOutbox = __t.object("EmailOutbox", {
  id: __t.u64(),
  identity: __t.identity(),
  toEmail: __t.string(),
  toName: __t.string(),
  sprintId: __t.u64(),
  kind: __t.string(),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
  amount: __t.u64(),
  perkTitle: __t.string(),
  mockRef: __t.string(),
});
export type EmailOutbox = __Infer<typeof EmailOutbox>;

export const EmailPumpTimer = __t.object("EmailPumpTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EmailPumpTimer = __Infer<typeof EmailPumpTimer>;

export const EventLog = __t.object("EventLog", {
  id: __t.u64(),
  kind: __t.string(),
  sprintId: __t.u64(),
  sessionCode: __t.string(),
  identity: __t.identity(),
  amount: __t.u64(),
  createdAt: __t.timestamp(),
});
export type EventLog = __Infer<typeof EventLog>;

export const FinalResult = __t.object("FinalResult", {
  sprintId: __t.u64(),
  finalCommittedAmount: __t.u64(),
  finalSupporterCount: __t.u32(),
  closedAt: __t.timestamp(),
});
export type FinalResult = __Infer<typeof FinalResult>;

export const Interest = __t.object("Interest", {
  id: __t.u64(),
  sprintId: __t.u64(),
  identity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Interest = __Infer<typeof Interest>;

export const Invite = __t.object("Invite", {
  id: __t.u64(),
  sprintId: __t.u64(),
  invitedUsername: __t.string(),
  invitedByUsername: __t.string(),
  createdAt: __t.timestamp(),
});
export type Invite = __Infer<typeof Invite>;

export const JourneyEntry = __t.object("JourneyEntry", {
  id: __t.u64(),
  sprintId: __t.u64(),
  position: __t.u32(),
  entryDate: __t.string(),
  text: __t.string(),
});
export type JourneyEntry = __Infer<typeof JourneyEntry>;

export const OwnerIdentity = __t.object("OwnerIdentity", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type OwnerIdentity = __Infer<typeof OwnerIdentity>;

export const ParticipantEmail = __t.object("ParticipantEmail", {
  identity: __t.identity(),
  email: __t.string(),
  sourceRef: __t.string(),
  createdAt: __t.timestamp(),
});
export type ParticipantEmail = __Infer<typeof ParticipantEmail>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
  username: __t.string(),
  bio: __t.string(),
  contact: __t.string(),
  location: __t.string(),
  socialX: __t.string(),
  socialLinkedin: __t.string(),
  socialInstagram: __t.string(),
});
export type Profile = __Infer<typeof Profile>;

export const RoomPresence = __t.object("RoomPresence", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  sprintId: __t.u64(),
  enteredAt: __t.timestamp(),
});
export type RoomPresence = __Infer<typeof RoomPresence>;

export const SiteConfig = __t.object("SiteConfig", {
  key: __t.string(),
  value: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SiteConfig = __Infer<typeof SiteConfig>;

export const Sprint = __t.object("Sprint", {
  id: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  nextStep: __t.string(),
  mediaUrl: __t.string(),
  builderName: __t.string(),
  goalAmount: __t.u64(),
  committedAmount: __t.u64(),
  supporterCount: __t.u32(),
  deadline: __t.timestamp(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  peakPresence: __t.u32(),
  builderBio: __t.string(),
  reserveAmount: __t.u64(),
  tagline: __t.string(),
  category: __t.string(),
  stage: __t.string(),
  builderCity: __t.string(),
  builderUsername: __t.string(),
  fundToolingPct: __t.u8(),
  fundComponentsPct: __t.u8(),
  fundCertPct: __t.u8(),
  fundBufferPct: __t.u8(),
  opensAt: __t.timestamp(),
  interestCount: __t.u32(),
});
export type Sprint = __Infer<typeof Sprint>;

export const SprintCloseTimer = __t.object("SprintCloseTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sprintId: __t.u64(),
});
export type SprintCloseTimer = __Infer<typeof SprintCloseTimer>;

export const SprintMedia = __t.object("SprintMedia", {
  id: __t.u64(),
  sprintId: __t.u64(),
  position: __t.u32(),
  thumb: __t.string(),
  full: __t.string(),
});
export type SprintMedia = __Infer<typeof SprintMedia>;

export const SprintOwner = __t.object("SprintOwner", {
  sprintId: __t.u64(),
  identity: __t.identity(),
});
export type SprintOwner = __Infer<typeof SprintOwner>;

export const SupportCommitment = __t.object("SupportCommitment", {
  id: __t.u64(),
  sprintId: __t.u64(),
  identity: __t.identity(),
  amount: __t.u64(),
  supportOptionId: __t.option(__t.u64()),
  mockTransactionId: __t.string(),
  createdAt: __t.timestamp(),
  quantity: __t.u32(),
  reserveAmount: __t.u64(),
});
export type SupportCommitment = __Infer<typeof SupportCommitment>;

export const SupportOption = __t.object("SupportOption", {
  id: __t.u64(),
  sprintId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  slotsTotal: __t.option(__t.u32()),
  slotsClaimed: __t.u32(),
  minAmount: __t.u64(),
});
export type SupportOption = __Infer<typeof SupportOption>;

